/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aplikasiperpustakaan;

/**
 *
 * @author asus
 */
public class FormDataAnggotaFix extends javax.swing.JFrame {

    /**
     * Creates new form FormDataAnggota
     */
    public FormDataAnggotaFix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nis = new javax.swing.JTextField();
        txt_namasiswa = new javax.swing.JTextField();
        txt_kelas = new javax.swing.JTextField();
        txt_kompetensi = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        txt_nis2 = new javax.swing.JTextField();
        txt_namasiswa2 = new javax.swing.JTextField();
        txt_kelas2 = new javax.swing.JTextField();
        txt_kompetensi2 = new javax.swing.JTextField();
        txt_alamat2 = new javax.swing.JTextField();
        rd_lk = new javax.swing.JRadioButton();
        rd_pr = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txt_jk2 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KELAS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM DATA ANGGOTA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 300, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ALAMAT");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIS:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NAMA SISWA");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("KELAS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("KOMPETENSI");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));
        jPanel2.add(txt_nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 120, -1));
        jPanel2.add(txt_namasiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 240, -1));
        jPanel2.add(txt_kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 100, -1));

        txt_kompetensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kompetensiActionPerformed(evt);
            }
        });
        jPanel2.add(txt_kompetensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 150, -1));

        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });
        jPanel2.add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 220, 100));

        btn_simpan.setBackground(new java.awt.Color(0, 0, 255));
        btn_simpan.setFont(new java.awt.Font("Segoe UI Historic", 1, 11)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("Simpan");
        btn_simpan.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });
        jPanel2.add(btn_simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 60, 40));

        btn_batal.setBackground(new java.awt.Color(204, 0, 0));
        btn_batal.setFont(new java.awt.Font("Segoe UI Historic", 1, 11)); // NOI18N
        btn_batal.setForeground(new java.awt.Color(255, 255, 255));
        btn_batal.setText("Hapus");
        btn_batal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonGroup1.add(btn_batal);
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel2.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 70, 40));
        jPanel2.add(txt_nis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 120, -1));
        jPanel2.add(txt_namasiswa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 240, -1));
        jPanel2.add(txt_kelas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 100, -1));

        txt_kompetensi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kompetensi2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_kompetensi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 150, -1));

        txt_alamat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamat2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_alamat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 220, 100));

        buttonGroup1.add(rd_lk);
        rd_lk.setForeground(new java.awt.Color(255, 255, 255));
        rd_lk.setText("laki-laki");
        rd_lk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_lkActionPerformed(evt);
            }
        });
        jPanel2.add(rd_lk, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, 20));

        buttonGroup1.add(rd_pr);
        rd_pr.setForeground(new java.awt.Color(255, 255, 255));
        rd_pr.setText("perempuan");
        rd_pr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_prActionPerformed(evt);
            }
        });
        jPanel2.add(rd_pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, 20));

        jLabel8.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("JENIS KELAMIN");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        txt_jk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jk2ActionPerformed(evt);
            }
        });
        jPanel2.add(txt_jk2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 100, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_kompetensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kompetensiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kompetensiActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        String nis,nama_siswa,kelas,kompetensi,alamat;
        
        String jk;
       if(rd_lk.isSelected()){
           jk = "L";
        } else{
           jk = "P";
       };
       
       
        
       nis = txt_nis.getText();
       nama_siswa = txt_namasiswa.getText();
       kelas = txt_kelas.getText();
       kompetensi = txt_kompetensi.getText();
       alamat = txt_alamat.getText();
       
       txt_nis2.setText(nis);
       txt_namasiswa2.setText(nama_siswa);
       txt_jk2.setText(jk);
       txt_kelas2.setText(kelas);
       txt_kompetensi2.setText(kompetensi);
       txt_alamat2.setText(alamat);
       
       
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
       txt_nis.setText("");
       txt_namasiswa.setText("");
       txt_kelas.setText("");
       txt_kompetensi.setText("");
       txt_alamat.setText("");
        
       txt_nis2.setText("");
       txt_namasiswa2.setText("");
       txt_kelas2.setText("");
       txt_jk2.setText("jk");
       txt_kompetensi.setText("");
       txt_alamat2.setText("");
       
       txt_nis.requestFocus();
       
    }//GEN-LAST:event_btn_batalActionPerformed

    private void txt_kompetensi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kompetensi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kompetensi2ActionPerformed

    private void txt_alamat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamat2ActionPerformed

    private void rd_lkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_lkActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rd_lkActionPerformed

    private void rd_prActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_prActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd_prActionPerformed

    private void txt_jk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jk2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDataAnggotaFix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDataAnggotaFix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDataAnggotaFix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataAnggotaFix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDataAnggotaFix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_simpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rd_lk;
    private javax.swing.JRadioButton rd_pr;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_alamat2;
    private javax.swing.JTextField txt_jk2;
    private javax.swing.JTextField txt_kelas;
    private javax.swing.JTextField txt_kelas2;
    private javax.swing.JTextField txt_kompetensi;
    private javax.swing.JTextField txt_kompetensi2;
    private javax.swing.JTextField txt_namasiswa;
    private javax.swing.JTextField txt_namasiswa2;
    private javax.swing.JTextField txt_nis;
    private javax.swing.JTextField txt_nis2;
    // End of variables declaration//GEN-END:variables
}
